"""Driver Generator - C/C++ code generation for hardware drivers.

Generates register-aware HAL code from the components and register map
extracted from GLR specification + RDT (Register Description Table).
"""

import logging
import re
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


class DriverGenerator:
    """Generate C driver code from hardware specifications."""

    def generate(
        self,
        project_name: str,
        components: List[Dict],
        registers: List[Dict],
        metadata: Optional[Dict] = None,
    ) -> Dict[str, str]:
        """
        Generate C HAL driver files.

        Args:
            project_name: Human-readable project name.
            components:   List of component dicts from _extract_components.
            registers:    List of register dicts from _extract_registers.
            metadata:     Optional dict with 'srs', 'sdd', 'rdt', 'psq' strings.

        Returns:
            Dict mapping filename -> file content.
        """
        metadata = metadata or {}
        rdt_text = metadata.get("rdt", "")
        psq_text = metadata.get("psq", "")

        # If register list is empty but RDT text is available, extract from text
        if not registers and rdt_text:
            registers = self._parse_registers_from_rdt(rdt_text)

        return {
            "hal.h":      self._generate_header(project_name, registers, components),
            "hal.c":      self._generate_source(project_name, registers, components),
            "hal_regs.h": self._generate_regs_header(project_name, registers),
            "Makefile":   self._generate_makefile(project_name),
        }

    # ------------------------------------------------------------------ #
    # hal_regs.h - register address / bit-field definitions
    # ------------------------------------------------------------------ #

    def _generate_regs_header(self, project_name: str, registers: List[Dict]) -> str:
        safe_name = project_name.replace(" ", "_").upper()
        guard = f"{safe_name}_HAL_REGS_H"

        lines = [
            f"/**",
            f" * @file hal_regs.h",
            f" * @brief Register address map for {project_name}",
            f" * @note  Auto-generated by Hardware Pipeline v2 - do not edit manually.",
            f" */",
            "",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#include <stdint.h>",
            "",
            "/* ================================================================",
            f" * Register Address Map - {project_name}",
            " * 16-bit UART address: bit15=R/W#, bits[11:8]=BASE, bits[7:0]=OFFSET",
            " * ================================================================ */",
            "",
        ]

        if registers:
            for reg in registers:
                name    = reg.get("name", "REG").upper()
                address = reg.get("address", "0x0000")
                desc    = reg.get("description", "")
                access  = reg.get("access", "RW")
                width   = reg.get("width", 16)
                lines += [
                    f"/** @brief {desc} (access: {access}, {width}-bit) */",
                    f"#define REG_{name:<30s} ({address}U)",
                    "",
                ]
        else:
            # Fallback defaults when no registers were found
            defaults = [
                ("CTRL",        "0x0000", "Control register",      "RW"),
                ("STATUS",      "0x0001", "Status register",        "RO"),
                ("VERSION",     "0x0002", "Firmware version",       "RO"),
                ("SCRATCHPAD",  "0x0003", "Read-write test register","RW"),
                ("IRQ_MASK",    "0x0F00", "Interrupt mask",         "RW"),
                ("IRQ_STATUS",  "0x0F01", "Interrupt status (W1C)", "RC"),
            ]
            for name, addr, desc, access in defaults:
                lines += [
                    f"/** @brief {desc} (access: {access}) */",
                    f"#define REG_{name:<30s} ({addr}U)",
                    "",
                ]

        lines += [
            "/* Common bit-field masks */",
            "#define BIT(n)          (1U << (n))",
            "#define REG_RW_FLAG     BIT(15)   /**< Set in address for Read operations */",
            "",
            f"#endif /* {guard} */",
        ]
        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    # hal.h - public API
    # ------------------------------------------------------------------ #

    def _generate_header(
        self,
        project_name: str,
        registers: List[Dict],
        components: List[Dict],
    ) -> str:
        safe_name  = project_name.replace(" ", "_").lower()
        guard      = f"{safe_name}_HAL_H"
        comp_names = ", ".join(c.get("name", "") for c in components[:5]) if components else "N/A"

        lines = [
            f"/**",
            f" * @file hal.h",
            f" * @brief Hardware Abstraction Layer for {project_name}",
            f" * @details Components: {comp_names}",
            f" * @note  Auto-generated by Hardware Pipeline v2",
            f" */",
            "",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#include <stdint.h>",
            "#include <stdbool.h>",
            f'#include "hal_regs.h"',
            "",
            "/* ================================================================",
            " * Error codes",
            " * ================================================================ */",
            "typedef enum {",
            "    HAL_OK            =  0,   /**< Success */",
            "    HAL_ERROR         = -1,   /**< Generic error */",
            "    HAL_BUSY          = -2,   /**< Resource busy */",
            "    HAL_TIMEOUT       = -3,   /**< Operation timed out */",
            "    HAL_INVALID_PARAM = -4,   /**< Invalid parameter */",
            "    HAL_NOT_INIT      = -5,   /**< HAL not initialised */",
            "} hal_status_t;",
            "",
            "/* ================================================================",
            " * Configuration",
            " * ================================================================ */",
            "typedef struct {",
            "    uint32_t clock_hz;        /**< System clock frequency in Hz */",
            "    uint32_t baud_rate;       /**< UART baud rate */",
            "    uint32_t timeout_ms;      /**< Default operation timeout (ms) */",
            "} hal_config_t;",
            "",
            "/* ================================================================",
            " * Register I/O primitives",
            " * ================================================================ */",
            "",
            "/**",
            " * @brief  Write a 16-bit value to a device register via UART.",
            " * @param  addr   Register address (16-bit, bit15=0 for write).",
            " * @param  value  Value to write.",
            " * @return HAL_OK on success.",
            " */",
            "hal_status_t hal_reg_write(uint16_t addr, uint16_t value);",
            "",
            "/**",
            " * @brief  Read a 16-bit value from a device register via UART.",
            " * @param  addr   Register address (16-bit, bit15=1 for read).",
            " * @param  value  Pointer to store the read value.",
            " * @return HAL_OK on success.",
            " */",
            "hal_status_t hal_reg_read(uint16_t addr, uint16_t *value);",
            "",
            "/* ================================================================",
            " * Lifecycle",
            " * ================================================================ */",
            "hal_status_t hal_init(const hal_config_t *cfg);",
            "hal_status_t hal_deinit(void);",
            "bool         hal_is_ready(void);",
            "",
            "/* ================================================================",
            " * High-level helpers",
            " * ================================================================ */",
            "",
        ]

        # Generate a typed accessor per named register
        if registers:
            for reg in registers[:20]:
                name   = reg.get("name", "REG").lower()
                access = reg.get("access", "RW")
                desc   = reg.get("description", "")
                if "R" in access.upper():
                    lines += [
                        f"/** @brief Read {desc} */",
                        f"hal_status_t hal_read_{name}(uint16_t *out);",
                        "",
                    ]
                if "W" in access.upper() or "RW" in access.upper():
                    lines += [
                        f"/** @brief Write {desc} */",
                        f"hal_status_t hal_write_{name}(uint16_t value);",
                        "",
                    ]

        lines += [f"#endif /* {guard} */"]
        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    # hal.c - implementation
    # ------------------------------------------------------------------ #

    def _generate_source(
        self,
        project_name: str,
        registers: List[Dict],
        components: List[Dict],
    ) -> str:
        safe_name = project_name.replace(" ", "_").lower()

        lines = [
            f"/**",
            f" * @file hal.c",
            f" * @brief Hardware Abstraction Layer implementation for {project_name}",
            f" * @note  Auto-generated by Hardware Pipeline v2",
            f" */",
            "",
            '#include "hal.h"',
            "#include <string.h>",
            "",
            "/* ================================================================",
            " * Private state",
            " * ================================================================ */",
            "static hal_config_t s_cfg    = {0U};",
            "static bool         s_ready  = false;",
            "",
            "/* ================================================================",
            " * Forward declarations (platform-specific - implement per BSP)",
            " * ================================================================ */",
            "static hal_status_t _uart_write_bytes(const uint8_t *buf, uint16_t len);",
            "static hal_status_t _uart_read_bytes (uint8_t *buf, uint16_t len, uint32_t timeout_ms);",
            "",
            "/* ================================================================",
            " * Register I/O",
            " * ================================================================ */",
            "",
            "hal_status_t hal_reg_write(uint16_t addr, uint16_t value)",
            "{",
            "    if (!s_ready) { return HAL_NOT_INIT; }",
            "    /* UART write frame: [0x57 'W'] [ADDR_MSB] [ADDR_LSB] [DATA_MSB] [DATA_LSB] */",
            "    uint8_t frame[5];",
            "    frame[0] = 0x57U;                          /* 'W' command byte   */",
            "    frame[1] = (uint8_t)((addr  >> 8U) & 0x7FU); /* MSB, bit15=0 write */",
            "    frame[2] = (uint8_t)(addr  & 0xFFU);",
            "    frame[3] = (uint8_t)((value >> 8U) & 0xFFU);",
            "    frame[4] = (uint8_t)(value & 0xFFU);",
            "    return _uart_write_bytes(frame, 5U);",
            "}",
            "",
            "hal_status_t hal_reg_read(uint16_t addr, uint16_t *value)",
            "{",
            "    hal_status_t status;",
            "    uint8_t rx[2];",
            "    uint8_t frame[3];",
            "    if (!s_ready)  { return HAL_NOT_INIT; }",
            "    if (value == NULL) { return HAL_INVALID_PARAM; }",
            "    /* UART read frame: [0x52 'R'] [ADDR_MSB|0x80] [ADDR_LSB] */",
            "    frame[0] = 0x52U;                          /* 'R' command byte   */",
            "    frame[1] = (uint8_t)((addr >> 8U) | 0x80U); /* MSB, bit15=1 read  */",
            "    frame[2] = (uint8_t)(addr & 0xFFU);",
            "    status = _uart_write_bytes(frame, 3U);",
            "    if (status != HAL_OK) { return status; }",
            "    status = _uart_read_bytes(rx, 2U, s_cfg.timeout_ms);",
            "    if (status != HAL_OK) { return status; }",
            "    *value = (uint16_t)(((uint16_t)rx[0] << 8U) | (uint16_t)rx[1]);",
            "    return HAL_OK;",
            "}",
            "",
            "/* ================================================================",
            " * Lifecycle",
            " * ================================================================ */",
            "",
            "hal_status_t hal_init(const hal_config_t *cfg)",
            "{",
            "    hal_status_t status;",
            "    uint16_t     scratch_rb;",
            "    if (cfg == NULL) { return HAL_INVALID_PARAM; }",
            "    if (s_ready)     { return HAL_OK; }            /* Idempotent */",
            "    (void)memcpy(&s_cfg, cfg, sizeof(hal_config_t));",
            "    s_ready = true;",
            "    /* Verify register bus: write SCRATCHPAD, read back */",
            "    status = hal_reg_write(REG_SCRATCHPAD, 0xA55AU);",
            "    if (status != HAL_OK) { s_ready = false; return status; }",
            "    status = hal_reg_read((uint16_t)(REG_SCRATCHPAD | 0x8000U), &scratch_rb);",
            "    if (status != HAL_OK) { s_ready = false; return status; }",
            "    if (scratch_rb != 0xA55AU) { s_ready = false; return HAL_ERROR; }",
            "    return HAL_OK;",
            "}",
            "",
            "hal_status_t hal_deinit(void)",
            "{",
            "    s_ready = false;",
            "    (void)memset(&s_cfg, 0, sizeof(hal_config_t));",
            "    return HAL_OK;",
            "}",
            "",
            "bool hal_is_ready(void)",
            "{",
            "    return s_ready;",
            "}",
            "",
            "/* ================================================================",
            " * High-level register accessors (auto-generated from RDT)",
            " * ================================================================ */",
            "",
        ]

        # Generate typed accessor implementations per register
        if registers:
            for reg in registers[:20]:
                name   = reg.get("name", "REG").lower()
                addr   = reg.get("address", "0x0000")
                access = reg.get("access", "RW")

                if "R" in access.upper():
                    lines += [
                        f"hal_status_t hal_read_{name}(uint16_t *out)",
                        "{",
                        f"    return hal_reg_read((uint16_t)({addr}U | 0x8000U), out);",
                        "}",
                        "",
                    ]
                if "W" in access.upper() or "RW" in access.upper():
                    lines += [
                        f"hal_status_t hal_write_{name}(uint16_t value)",
                        "{",
                        f"    return hal_reg_write((uint16_t)({addr}U & 0x7FFFU), value);",
                        "}",
                        "",
                    ]

        # BSP stubs
        lines += [
            "/* ================================================================",
            " * BSP stubs - implement these for your target platform",
            " * ================================================================ */",
            "",
            "static hal_status_t _uart_write_bytes(const uint8_t *buf, uint16_t len)",
            "{",
            "    /* TODO: implement for your UART peripheral (STM32 HAL, Arduino, etc.) */",
            "    (void)buf; (void)len;",
            "    return HAL_OK;",
            "}",
            "",
            "static hal_status_t _uart_read_bytes(uint8_t *buf, uint16_t len, uint32_t timeout_ms)",
            "{",
            "    /* TODO: implement for your UART peripheral */",
            "    (void)buf; (void)len; (void)timeout_ms;",
            "    return HAL_OK;",
            "}",
        ]

        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    # Makefile
    # ------------------------------------------------------------------ #

    def _generate_makefile(self, project_name: str) -> str:
        target = project_name.replace(" ", "_").lower()
        return f"""# Makefile for {project_name}
# Generated by Hardware Pipeline v2

CC      = gcc
CFLAGS  = -Wall -Wextra -Wpedantic -O2 -std=c11 -Isrc
LDFLAGS =

SRCDIR  = src
OBJDIR  = obj
SOURCES = $(wildcard $(SRCDIR)/*.c)
OBJECTS = $(SOURCES:$(SRCDIR)/%.c=$(OBJDIR)/%.o)
TARGET  = {target}_driver

.PHONY: all clean cppcheck

all: $(TARGET)

$(TARGET): $(OBJECTS)
\t$(CC) $(LDFLAGS) -o $@ $^

$(OBJDIR)/%.o: $(SRCDIR)/%.c | $(OBJDIR)
\t$(CC) $(CFLAGS) -c $< -o $@

$(OBJDIR):
\tmkdir -p $(OBJDIR)

cppcheck:
\tcppcheck --enable=all --std=c11 --suppress=missingIncludeSystem \\
\t         --error-exitcode=1 $(SRCDIR)/

clean:
\trm -rf $(OBJDIR) $(TARGET)
"""

    # ------------------------------------------------------------------ #
    # Save
    # ------------------------------------------------------------------ #

    def save(self, files: Dict[str, str], output_dir: Path) -> List[Path]:
        output_dir = Path(output_dir)
        src_dir    = output_dir / "src"
        src_dir.mkdir(parents=True, exist_ok=True)

        saved = []
        for filename, content in files.items():
            filepath = output_dir / filename if filename == "Makefile" else src_dir / filename
            filepath.write_text(content, encoding="utf-8")
            saved.append(filepath)
        return saved

    # ------------------------------------------------------------------ #
    # Internal helpers
    # ------------------------------------------------------------------ #

    def _parse_registers_from_rdt(self, rdt_text: str) -> List[Dict]:
        """Parse a basic register list from RDT markdown text."""
        registers = []
        # Match table rows: | `NAME` | `0x0000` | ...
        pattern = re.compile(
            r"\|\s*`([A-Z_][A-Z0-9_]*)`\s*\|\s*`(0x[0-9A-Fa-f]+)`\s*\|"
            r"[^|]*\|[^|]*\|\s*([^|]+?)\s*\|"
        )
        seen = set()
        for m in pattern.finditer(rdt_text):
            name, addr, desc = m.group(1), m.group(2), m.group(3).strip()
            if name not in seen:
                seen.add(name)
                # Infer access type from description
                access = "RO" if "read-only" in desc.lower() or " ro" in desc.lower() else \
                         "RC" if "read-clear" in desc.lower() or " rc" in desc.lower() else "RW"
                registers.append({
                    "name":        name,
                    "address":     addr,
                    "access":      access,
                    "width":       16,
                    "description": desc[:80],
                })
        return registers

    def _default_components(self) -> List[Dict]:
        return [
            {"name": "MCU",  "type": "Microcontroller", "description": "Main processor"},
            {"name": "FPGA", "type": "Programmable logic", "description": "Glue logic device"},
        ]

    def _default_registers(self) -> List[Dict]:
        return [
            {"name": "CTRL",       "address": "0x0000", "access": "RW", "width": 16, "description": "Control register"},
            {"name": "STATUS",     "address": "0x0001", "access": "RO", "width": 16, "description": "Status register"},
            {"name": "VERSION",    "address": "0x0002", "access": "RO", "width": 16, "description": "Firmware version"},
            {"name": "SCRATCHPAD", "address": "0x0003", "access": "RW", "width": 16, "description": "R/W test register"},
            {"name": "IRQ_MASK",   "address": "0x0F00", "access": "RW", "width": 16, "description": "Interrupt mask"},
            {"name": "IRQ_STATUS", "address": "0x0F01", "access": "RC", "width": 16, "description": "Interrupt status (W1C)"},
        ]
